### ISSUE TITLE
Add include

### ISSUE THREAD

**Issue by ThomDevs** [vikbez/hfsync#1]
Une requête pour hfsync :
- serait-il possible d'avoir une sorte d'include spécifique à proposer au soft en command line ?
  Cet include ne tiendrai pas compte des exclude dans le ini, et ne téléchargerai QUE les fichiers précisés (pouvoir en mettre plusieurs serait bien, avec un spéparateur genre "pipe").
  ex: hfsync -include="Databases\Main Menu\Main Menu.xml|Databases\Capcom Play System\Capcom Play System.xml" 

En fait, je voudrais télécharger uniquement des fichiers précis de la box (sans le reste), pour les lire et les travailler avant de proposer des options permettant de tout télécharger ou pas. Les exclude c'est bien, mais ne connaissant pas TOUT ce qu'il y a dans la box, je dois procéder par inversion ... et c'est pas forcément le plus pratique pour moi.

Merci !

**Comment by moul** [comment]
:+1:

**Comment by vikbez** [comment]
Implemented (https://github.com/vikbez/hfsync/commit/de1d2ab191f872c180de55172e623fe3bd11e0d7)

[Released in 1.0.9](https://github.com/vikbez/hfsync/releases/tag/v1.0.9-snapshot)
